# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserTransactionsLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('log', models.TextField(blank=True, default='', null=True)),
                ('old_balance', models.TextField(blank=True, default='', null=True)),
                ('new_balance', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
