# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smsangosend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVolumePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayStackPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amtcredited', models.FloatField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('smsangosbulkcredit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_purchase', to='smsangosend.smsangosbulkcredit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payments & Voucher Histories',
                'managed': True,
            },
        ),
    ]
