# Generated by Django 3.2 on 2021-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=100)),
                ('task_parameters', models.JSONField(default=dict)),
                ('task_hash', models.CharField(default='', max_length=20)),
                ('task_status', models.CharField(default='Done', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=100)),
                ('task_parameters', models.JSONField(default=dict)),
                ('task_hash', models.CharField(default='', max_length=20)),
                ('task_status', models.CharField(default='Not Done', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
