# Generated by Django 3.2.13 on 2022-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyactivation',
            name='api_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikeyactivation',
            name='domain',
            field=models.CharField(blank='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apikeyactivation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
