# Generated by Django 3.2 on 2024-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220627_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('url_data', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sms_url', models.TextField(blank=True, null=True)),
                ('sms_url_data', models.TextField(blank=True, null=True)),
                ('sms_success_code', models.TextField(blank=True, null=True)),
                ('success_code', models.CharField(blank=True, max_length=200, null=True)),
                ('kyc_cost', models.FloatField(default=0.0)),
                ('kyc_type', models.CharField(choices=[('BVN', 'BVN'), ('NIN', 'NIN')], default='BVN', max_length=20)),
                ('do_verifcation', models.BooleanField(default=False)),
            ],
        ),
    ]
