# Generated by Django 3.2 on 2021-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_domain', models.CharField(default='vbp.com', help_text='domain name of this site', max_length=50)),
                ('site_name', models.CharField(default='VBP', max_length=20)),
                ('phone', models.CharField(default='', help_text='format: 2348163524890', max_length=13)),
                ('email', models.EmailField(default='', max_length=254)),
                ('keywords', models.TextField(default='VBP', max_length=2000)),
                ('Site Description', models.TextField(default='VBP - Best VTU site', max_length=2000)),
                ('gradient_background_color1', models.CharField(default='#df4ec3', max_length=20)),
                ('gradient_background_color2', models.CharField(default='#be22a8', max_length=20)),
                ('button_color1', models.CharField(default='#bddf4e', max_length=20)),
                ('button_color2', models.CharField(default='#000', max_length=20)),
                ('menu_color', models.CharField(default='#fff', max_length=20)),
                ('site_logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('paystack_sk_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('paystack_pk_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount_funding_limit_through_paysatack', models.PositiveIntegerField(default=2450)),
                ('amount_funding_percentage', models.FloatField(default=0.016, help_text='0.016 means 1.6% it is the commission paystack will deduct')),
                ('bank_account_no', models.CharField(default='0108497080', max_length=15)),
                ('bank_name', models.CharField(default='GTbank', max_length=300)),
                ('account_name', models.CharField(default='OLAYANJU AZEEZ AJIBOLA', max_length=300)),
                ('require_activation', models.BooleanField(default=False, help_text='This enable activation email to be sent to user before they can login', verbose_name='Allow User to Activate Account')),
                ('allow_payment_for_apikey', models.BooleanField(default=False, verbose_name='Allow User to Pay to access your API')),
                ('amount_to_pay_for_apikey', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(default='https://otextcity.com/app/cc/noted?site={0}&phone={1}&email={2}&li_value={3}', editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Dashboard Configuration',
                'verbose_name_plural': 'Site Dashboard Configurations',
            },
        ),
        migrations.CreateModel(
            name='SmtpEmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_email_host', models.CharField(default='smtp.example.com', max_length=500)),
                ('smtp_email_host_user', models.CharField(default='apikey', max_length=500)),
                ('smtp_email_host_sender_address', models.CharField(default='example@example.com', max_length=500)),
                ('smtp_email_host_password', models.CharField(default='password', max_length=500)),
                ('smtp_email_host_port', models.IntegerField(default='587')),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_timeout', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
