# Generated by Django 3.2.13 on 2022-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreconfig', '0002_auto_20220626_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='api_text',
            field=models.CharField(default='can be any thing', help_text='this is the text the api consuming will input on there domain to verify them', max_length=500, null=True),
        ),
    ]
