# Generated by Django 3.2.13 on 2022-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreconfig', '0003_dashboardconfig_api_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='admin_url',
            field=models.CharField(default='admin', max_length=300),
        ),
    ]
