# Generated by Django 3.2 on 2023-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreconfig', '0004_dashboardconfig_admin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayOfApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_sms', models.BooleanField(default=True)),
                ('show_airtime', models.BooleanField(default=True)),
                ('show_data', models.BooleanField(default=True)),
                ('show_broadband', models.BooleanField(default=True)),
                ('show_cable', models.BooleanField(default=True)),
                ('show_electricity', models.BooleanField(default=True)),
                ('show_recharge_pin', models.BooleanField(default=True)),
                ('show_datapin', models.BooleanField(default=True)),
                ('show_crypto', models.BooleanField(default=True)),
                ('show_news', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_transfer_app', models.BooleanField(default=True)),
                ('show_wallet_transfer', models.BooleanField(default=True)),
                ('show_universal_rcp', models.BooleanField(default=True)),
                ('show_reseller', models.BooleanField(default=True)),
                ('show_insurance', models.BooleanField(default=True)),
                ('show_investment', models.BooleanField(default=True)),
            ],
        ),
    ]
