# Generated by Django 3.2 on 2022-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackCableRecharegAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('callback_success_code', models.CharField(default='ORDER_COMPLETED', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API For Cable Callback',
                'verbose_name_plural': 'API For Cable Callbacks',
            },
        ),
        migrations.CreateModel(
            name='CallbackDataNetworksApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('callback_success_code', models.CharField(default='ORDER_COMPLETED', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API For Data Recharge Callback',
                'verbose_name_plural': 'APIs For Data Recharge Callbacks',
            },
        ),
        migrations.CreateModel(
            name='CallbackRechargeAirtimeAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('callback_success_code', models.CharField(default='ORDER_COMPLETED', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API For Airtime Recharge Callback',
                'verbose_name_plural': 'APIs For Airtime Recharge Callbacks',
            },
        ),
    ]
