# Generated by Django 3.2.13 on 2022-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackElectricityAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('callback_success_code', models.CharField(default='ORDER_COMPLETED', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API For Cable Callback',
                'verbose_name_plural': 'API For Cable Callbacks',
            },
        ),
    ]
