# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, default='Default', max_length=10, null=True)),
                ('apurl', models.TextField(blank=True, null=True)),
                ('apurl_data', models.JSONField(default=dict, help_text='{"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "to":"[TO]", "sender":"[SENDER]", "message":"[MESSAGE]"}, "headers":{"authorization":"Bearer API_KEY"}}')),
                ('apiamtpersms', models.DecimalField(decimal_places=1, default=2, max_digits=10, null=True)),
                ('api_response', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_active', models.BooleanField()),
                ('send_one_by_one', models.BooleanField(default=False, help_text="<strong style='color:red;'>if API can accept unlimited request per seconds check to True else False</strong>")),
            ],
            options={
                'verbose_name': 'SMS API',
                'verbose_name_plural': 'SMS APIs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('refferal', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsangoSendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('sender', models.CharField(max_length=11)),
                ('recipients', models.TextField(help_text='Seperate each Items by comma')),
                ('messagecontent', models.TextField()),
                ('notsently', models.TextField(blank=True, null=True)),
                ('sently', models.TextField(blank=True, null=True)),
                ('apiRoute', models.CharField(default='NON DND ROUTE', max_length=15)),
                ('status', models.CharField(max_length=200)),
                ('creditusedall', models.CharField(default='', max_length=10)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsangosendsms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsangoSBulkCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smscredit', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smsbulkcredit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit Balance',
                'verbose_name_plural': 'User Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=11)),
                ('recipients', models.TextField(help_text='Seperate each Items by comma')),
                ('messagecontent', models.TextField()),
                ('notsently', models.TextField(blank=True, null=True)),
                ('sently', models.TextField(blank=True, null=True)),
                ('apiRoute', models.CharField(default='NON DND ROUTE', max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('time_to_send', models.DateTimeField()),
                ('creditusedall', models.CharField(default='', max_length=10)),
                ('scheduleidnum', models.CharField(default='', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulesendsms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedScheduledSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=11)),
                ('recipients', models.TextField(help_text='Seperate each Items by comma')),
                ('messagecontent', models.TextField()),
                ('smsroute', models.CharField(default='', max_length=10)),
                ('time_to_send', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('scheduleidnum', models.CharField(default='', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedschedulesendsms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Scheduled SMS',
                'verbose_name_plural': 'Saved Scheduled SMS',
            },
        ),
        migrations.CreateModel(
            name='PhoneBookContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contacts', models.CharField(default='', max_length=20)),
                ('contact_numbers', models.TextField(default='', max_length=6000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
