# Generated by Django 3.2.13 on 2022-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsangosend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
