# Generated by Django 3.2.13 on 2022-06-26 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsangosend', '0002_userprofile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsangosendsms',
            name='numcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='pages',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='scheduledsms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='scheduleidnum',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='smsroute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='time_to_send',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsangosendsms',
            name='totalsms',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='ScheduleSendSMS',
        ),
    ]
