# Generated by Django 3.2 on 2024-01-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsangosend', '0004_alter_smsangosendsms_time_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bvn_kyc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_verification',
            field=models.BooleanField(default=False, help_text='this is for bvn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_verification_nin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nin_kyc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_response',
            field=models.TextField(blank=True, help_text='this is for bvn', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_response_nin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
