# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusesPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.CharField(default='', max_length=30)),
                ('purchase_airtime_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('purchase_data_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('purchase_cable_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('purchase_electricity_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('education_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('spectranet_bonus', models.TextField(default='{"spectranet_bonus": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('smile_bonus', models.TextField(default='{"smile_bonus": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_airtime_bonus', models.TextField(default='{"identifier": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_data_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_cable_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_electricity_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_pin_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_bonus', models.FloatField(blank=True, default=0.0, help_text='Referral is not in percentage but actual value e.g 400.0 etc it used for giving signup bonuses to A who referred B when B signs up', null=True)),
                ('referral_education_bonus', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_smile_bonus', models.TextField(default='{"smile_bonus": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_spectranet_bonus', models.TextField(default='{"spectranet_bonus": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_activation_reseller_bonus', models.TextField(default='{"reseller_plan_name": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('referral_upgrade_reseller_bonus', models.TextField(default='{"reseller_plan_name": 0.01}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('signup_bonus', models.FloatField(blank=True, default=0.0, help_text='amount given to a user when they sign up actual values e.g 200', null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPricePerSMSToPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceperunit', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('lowprice', models.PositiveIntegerField(default=1, null=True)),
                ('highprice', models.PositiveIntegerField(default=9999, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Default Price Per Credit To Purchase',
                'verbose_name_plural': 'Default Price Per Credit To Purchase',
            },
        ),
        migrations.CreateModel(
            name='PricingPerSMSPerUserToPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=1.0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smspricingperuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Per Credit Per User To Purchase',
                'verbose_name_plural': 'Pricing Per Credit Per User To Purchase',
            },
        ),
    ]
