# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerLevelsAndPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lever One Reseller', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('cost_of_activation', models.FloatField(default=0.0, help_text='amount to be paid by the user to join this level of reseller')),
                ('fund_to_wallet', models.FloatField(default=1000.0, help_text='Minimum amount to fund into wallet')),
                ('airtime', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('data', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('education', models.TextField(default='{"education1": 0.01, "education2":0.02}', help_text='this should be in json format e.g {"education1": 0.01, "education2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('electricity', models.TextField(default='{"electicity1": 0.01, "electicity2":0.02}', help_text='this should be in json format e.g {"electicity1": 0.01, "electicity2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('cable_tv', models.TextField(default='{"cable1": 0.01, "cable2":0.02}', help_text='this should be in json format e.g {"cable1": 0.01, "cable2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('insurance', models.TextField(default='{"Private": 0.01}', help_text='this should be in json format e.g {"Private": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('health_insurance', models.TextField(default='{"individual-monthly": 0.01}', help_text='this should be in json format e.g {"individual-monthly": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('home_cover', models.TextField(default='{"individual-monthly": 0.01}', help_text='this should be in json format e.g {"individual-monthly": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('personal_insurance', models.TextField(default='{"individual-monthly": 0.01}', help_text='this should be in json format e.g {"individual-monthly": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('decoded_card_printing', models.TextField(default='{"network1": 0.01, "network2":0.02}', help_text='this should be in json format e.g {"network1": 0.01, "network2":0.02} where 0.01 means 1%, network1 is the network code as in your API')),
                ('smile', models.TextField(default='{"sms": 0.01}', help_text='this should be in json format e.g {"sms": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('mtn_sme', models.TextField(default='{"sms": 0.01}', help_text='this should be in json format e.g {"sms": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('spectranet', models.TextField(default='{"sms": 0.01}', help_text='this should be in json format e.g {"sms": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
                ('sms', models.TextField(default='{"sms": 0.01}', help_text='this should be in json format e.g {"sms": 0.01} where 0.01 means 1%, her only the percentage amount should be affected leave "sms" as is on change the 0.01 to your preferred percentage')),
            ],
        ),
        migrations.CreateModel(
            name='ResellerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reseller', models.BooleanField(default=False)),
                ('reseller_level', models.CharField(default='Not a Reseller', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_reseller_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('reseller_level', models.CharField(default='', max_length=100)),
                ('previous_reseller_level', models.CharField(default='', max_length=100)),
                ('action', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reseller_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
