# Generated by Django 3.2.13 on 2022-06-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smsangosend', '0002_userprofile_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('identifier', models.CharField(default='', max_length=50)),
                ('bill_type', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_code', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_serial', models.CharField(blank=True, max_length=500, null=True)),
                ('actual_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, max_length=300, null=True)),
                ('customernumber', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('customername', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_dt_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('insured_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('engine_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('chasis_number', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('plate_number', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('vehicle_make', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('vehicle_color', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('year_of_make', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('photo', models.TextField(blank=True, default='', max_length=100000, null=True)),
                ('extra_info', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('type_building', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('business_occupation', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('api_id', models.IntegerField(blank=True)),
                ('amtcredited', models.FloatField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smsangosbulkcredit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_funding', to='smsangosend.smsangosbulkcredit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
