# Generated by Django 3.2.13 on 2022-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactions_call_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='call_url',
            new_name='callback_url',
        ),
        migrations.AddField(
            model_name='transactions',
            name='callback_done',
            field=models.BooleanField(default=False),
        ),
    ]
