# Generated by Django 3.2.13 on 2022-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20220626_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
