# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCheckerAPIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/waec', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}, then edit suit you')),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('result_checker_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='')),
                ('pin_code_json', models.TextField(default='[api_price|site_price|what_the_user_see]', max_length=1000)),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "pin", "serialNumber"] as seen on the API response', max_length=3000)),
                ('success_code', models.CharField(default='success', max_length=500)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'ResultChecker API',
                'verbose_name_plural': 'ResultChecker APIs',
            },
        ),
        migrations.CreateModel(
            name='ResultCheckers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('pin', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('serial_number', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('pin_type', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('api_response', models.TextField(blank=True, default='', max_length=13000, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_check_buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ResultCheckers Transaction',
                'verbose_name_plural': 'ResultCheckers Transactions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
