# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='1app', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/elect', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "account":"[METER_NO]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]", "custnam":"[CUSTOMER_NAME]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}, then edit suit you')),
                ('identifier', models.CharField(default='airtime', help_text='this should be a unique identifier', max_length=50)),
                ('electricity_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='')),
                ('api_url_check', models.TextField(default='https://{{request.get_host}}/app/api/v1/check_electricity?meterNo=[METER_NO]&service=[SERVICE]', max_length=1000)),
                ('api_url_balance', models.TextField(default='None', max_length=1000)),
                ('electricity_code_json', models.TextField(default='EKO_POSTPAID|Eko Electricity Distribution Postpaid|13|Eko Postpaid', max_length=5000)),
                ('metertype_code_json', models.TextField(default='["01|Prepaid","02|Postpaid"]', max_length=500)),
                ('check_success_code', models.CharField(default='customerName', max_length=500)),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "pin", "serialNumber"] as seen on the API response')),
                ('commission', models.FloatField(default=0.0)),
                ('success_code', models.CharField(default='success', max_length=500)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'ElectricityApi',
                'verbose_name_plural': 'ElectricityApis',
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='electricity_code', help_text='this should be a unique identifier', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('service', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('meter_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('customer_address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('customer_account_type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('customer_dt_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('api_response', models.TextField(blank=True, default='', null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elctricity_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electricity Transaction',
                'verbose_name_plural': 'Electricity Transactions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
