# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableRecharegAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/cable', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "iuc":"[SMART_NO]", "type":"[SERVICE]","amount":"[PLAN_AMOUNT]", "custno":"[CUSTOMER_NUMBER]", "custname":"[CUSTOMER_NAME]", "txref":"[ORDER_NUMBER]"}, "headers":{"authorization":"Bearer API_KEY"}}, then edit suit you')),
                ('api_url_balance', models.TextField(default='https://apiname.online/api/balance?userid=[Enter_userid]&apikey=[Apikey]', max_length=1000)),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('cable_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='')),
                ('customerCheck', models.TextField(default='https://{{request.get_host}}/app/customer/recharge/cable-check.aspx?smart_no=[SMART_NO]&service=[SERVICE]', max_length=1000)),
                ('cable_type_price', models.TextField(default='["|select a DSTV package", "ACSSE36|DStv Access = N2000 + Convinience fee N50|2050|2050", "FTAE36|DStv FTA Plus = N1600 + Convinience fee N50|1650|1650", "COFAME36|DStv Family = N4000 + Convinience fee N50|4050|4050", "ASIAE36|DstvAsiaBouqet = N5400 + Convinience fee N50|5450|5450", "COMPE36|DStv Compact = N6800 + Convinience fee N50|6850|6850", "COMPLE36|DStv Plus = N10650 + Convinience fee N50|10700|10700", "PRWE36|Dstv Premium = N15800 + Convinience fee N50|15850|15850", "DPRHD|DStv Premium Asia Ex= N19900 + Convinience fee N50|19950|19950", "DPRHDP|Dstv Premium Extra = N18000 + Convinience fee N50|18050|18050"]', help_text='<span class="text-danger">["api_code|what_user_sees|api_price|site_price|site_service_code"]</span>', max_length=13000)),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('successCheckCode', models.CharField(default='true', max_length=500)),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "variabletwo"] as seen on the API response', max_length=3000)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Cable Recharge',
                'verbose_name_plural': 'APIs For Cable Recharge',
            },
        ),
        migrations.CreateModel(
            name='DataNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('network_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='')),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('api_url', models.TextField(default='https://apiname.online/api/databundle', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "network_id":"[urlvariable]", "amount":"[apiamount]", "datacode":"[dataplan]","phoneno":"[phone]"}, "headers":{"authorization":"Bearer API_KEY"}}, then edit suit you')),
                ('api_url_balance', models.TextField(default='https://apiname.online/api/balance?userid=[Enter_userid]&apikey=[Apikey]', max_length=1000)),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('network_data_amount_json', models.TextField(default='[220|500MB_(SME)|1|500MB (SME)@NGN220,410|1GB_(SME)|1|1GB (SME)@NGN410]', help_text="<strong style='color:red;'>apiamount|data_amount|portal_api_code|what_user_sees'</strong>", max_length=13000)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Data Recharge',
                'verbose_name_plural': 'APIs For Data Recharge',
            },
        ),
        migrations.CreateModel(
            name='DataPlansPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('airtel', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('glo', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('nine_mobile', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeAirtimeAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('network_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='')),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('api_url', models.TextField(default='https://apiname.online/api/airtime', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "network_id":"[network_code]", "amount":"[amt]", "phoneno":"[phone]"}, "headers":{"authorization": "Bearer (API_KEY)"}}, then edit suit you')),
                ('api_url_balance', models.TextField(default='https://apiname.online/api/balance?userid=[Enter_userid]&apikey=[Apikey]', max_length=1000)),
                ('user_discount', models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>")),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Airtime Recharge',
                'verbose_name_plural': 'APIs For Airtime Recharge',
            },
        ),
        migrations.CreateModel(
            name='RefBonusAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refbonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('refoldbonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('redeemed', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuser_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MtnDataShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=50)),
                ('ordernumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('data_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('data_network', models.CharField(blank=True, default='MTN', max_length=20, null=True)),
                ('dataSize', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('data_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('batchno', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('api_response', models.TextField(blank=True, default='', null=True)),
                ('status', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mtndatashare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Top Up',
                'verbose_name_plural': 'Data TopUps',
            },
        ),
        migrations.CreateModel(
            name='CableRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=50)),
                ('ordernumber', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('invoice', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sub_amount', models.FloatField(blank=True, default=0, null=True)),
                ('smart_no', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('billtype', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('customernumber', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('customername', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('exchange_reference', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('messageresp', models.TextField(blank=True, default='', null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cablerecharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonusAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldbonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirtimeTopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=50)),
                ('ordernumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('recharge_amount', models.FloatField(blank=True, default=0, null=True)),
                ('recharge_network', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('recharge_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('api_response', models.TextField(blank=True, default='', null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('status', models.TextField(blank=True, default='', max_length=20, null=True)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_airtime', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
