# Generated by Django 3.2.13 on 2022-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanetworks',
            name='network_data_amount_json',
            field=models.TextField(default='220|500MB_(SME)|1|500MB (SME)@NGN220|extravariable,410|1GB_(SME)|1|1GB (SME)@NGN410|extravariable', help_text="<strong style='color:red;'>apiamount|data_amount|portal_api_code|what_user_sees|extravariable'</strong>", max_length=13000),
        ),
    ]
