# Generated by Django 2.0.6 on 2020-12-12 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapppurchaseaccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_whatsapp_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
