# Generated by Django 3.2.6 on 2022-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0002_auto_20201212_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(default='whatsapp', max_length=20)),
            ],
        ),
    ]
