# Generated by Django 3.2 on 2021-10-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntAirtimeApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/smile', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('check_api_url', models.TextField(default='https://apiname.online/api/smile', max_length=1000)),
                ('check_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "pin", "serialNumber"] as seen on the API response', max_length=3000)),
                ('success_code', models.CharField(default='success response', max_length=500)),
                ('success_check_code', models.CharField(default='success response', max_length=500)),
            ],
            options={
                'verbose_name': 'International Airtime API',
                'verbose_name_plural': 'International Airtime APIs',
            },
        ),
        migrations.CreateModel(
            name='MtnSMEApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_api_url', models.TextField(default='https://apiname.online/api/mtnSME', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('mtn_sme_code_json', models.TextField(default='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', help_text='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', max_length=5000)),
                ('success_code', models.CharField(default='success response', max_length=500)),
            ],
            options={
                'verbose_name': 'MTN SME API',
                'verbose_name_plural': 'MTN SME APIs',
            },
        ),
        migrations.CreateModel(
            name='SmilesApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/smile', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('check_api_url', models.TextField(default='https://apiname.online/api/smile', max_length=1000)),
                ('check_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('smile_code_json', models.TextField(default='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', help_text='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', max_length=5000)),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "pin", "serialNumber"] as seen on the API response', max_length=3000)),
                ('success_code', models.CharField(default='success response', max_length=500)),
                ('success_check_code', models.CharField(default='success response', max_length=500)),
            ],
            options={
                'verbose_name': 'SMILE API',
                'verbose_name_plural': 'SMILE APIs',
            },
        ),
        migrations.CreateModel(
            name='SpectranetApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://apiname.online/api/spectranet', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this =>{"data":{"apikey":"[APIKEY]", "userid":"[USER_ID]", "typeno":"[SERVICE_CODE]", "typename":"[SERVICE_NAME]", "amount":"[AMOUNT]", "txref":"[TRANSACTION_ID]"}, "headers":{"AUTHORIZATION":"API_KEY OR SOMETHING"}}')),
                ('spectranet_code_json', models.TextField(default='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', help_text='["api_code|what_user_sees|api_price|site_price|product_code|urlvariable|extra_parameter"]', max_length=5000)),
                ('res_params', models.TextField(default='', help_text='The responses from api to display to the users e.g ["code", "pin", "serialNumber"] as seen on the API response', max_length=3000)),
                ('success_code', models.CharField(default='success response', max_length=500)),
            ],
            options={
                'verbose_name': 'SPECTRANET API',
                'verbose_name_plural': 'SPECTRANET APIs',
            },
        ),
        migrations.CreateModel(
            name='SpectranetTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('api_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('numberRecharged', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('resp', models.TextField(blank=True, default='', null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectranet_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spectranet Transaction',
                'verbose_name_plural': 'Spectranet Transactions',
            },
        ),
        migrations.CreateModel(
            name='SmileTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('api_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('numberRecharged', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('smileType', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('resp', models.TextField(blank=True, default='', null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smile Transaction',
                'verbose_name_plural': 'Smile Transactions',
            },
        ),
        migrations.CreateModel(
            name='IntAirtimeTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('api_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('numberRecharged', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('network_recharged', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('resp', models.TextField(blank=True, default='', null=True)),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_airtime_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'International Airtime Transaction',
                'verbose_name_plural': 'International Airtime Transactions',
            },
        ),
    ]
