# Generated by Django 3.2 on 2022-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_data_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intairtimeapi',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
