# Generated by Django 3.2 on 2022-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=500)),
                ('email_content', models.TextField(blank=True, max_length=10000, null=True)),
                ('recipient', models.TextField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(blank=True, default='Sent', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmtpEmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_email_host', models.CharField(default='smtp.example.com', max_length=500)),
                ('smtp_email_host_user', models.CharField(default='apikey', max_length=500)),
                ('smtp_email_host_sender_address', models.CharField(default='example@example.com', max_length=500)),
                ('smtp_email_host_password', models.CharField(default='password', max_length=500)),
                ('smtp_email_host_port', models.IntegerField(default='587')),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_timeout', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
