# Generated by Django 3.1 on 2021-08-14 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonnifyKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(default='', max_length=200)),
                ('clientSecret', models.CharField(default='', max_length=200)),
                ('currencyCode', models.CharField(default='NGN', max_length=10)),
                ('contractCode', models.CharField(default='', max_length=200)),
                ('fee', models.FloatField(default=0.0, help_text='percentage amount to deduct from the transferred amount e.g 0.9% means 0.009')),
                ('maxAmountToDeductFee', models.FloatField(default=0.0, help_text='maximum amount by which the fee above will apply')),
                ('maxAmountFeeToDeduct', models.FloatField(default=0.0, help_text='The maximum fee to deduct when the maximum amount is exceeded')),
                ('source_account_number', models.CharField(blank=True, default='99999', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonnifyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountReference', models.CharField(default='', max_length=50, unique=True)),
                ('accountNumber', models.CharField(default='', max_length=50)),
                ('currencyCode', models.CharField(default='', max_length=50)),
                ('contractCode', models.CharField(default='', max_length=50)),
                ('accountName', models.CharField(default='', max_length=50)),
                ('customerEmail', models.CharField(default='', max_length=50)),
                ('bankName', models.CharField(default='', max_length=50)),
                ('bankCode', models.CharField(default='', max_length=50)),
                ('reservationReference', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_monnify_acc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
