# Generated by Django 3.2 on 2024-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnify_app', '0002_auto_20220423_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='monnifykeys',
            name='monnify_card_fee',
            field=models.FloatField(default=0.0, help_text='this is the fee ravepay charges in percentage so 0.09 means 9% of the funds to be paid'),
        ),
        migrations.AddField(
            model_name='monnifykeys',
            name='monnify_card_funding_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
