# Generated by Django 3.2 on 2021-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaveConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ravepay', help_text='Get the public and secret key here https://dashboard.flutterwave.com/dashboard/settings/apis', max_length=50)),
                ('public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('encryption_key', models.CharField(blank=True, max_length=100, null=True)),
                ('rave_fee', models.FloatField(default=0.0, help_text='this is the fee ravepay charges in percentage so 0.09 means 9% of the funds to be paid')),
                ('funding_limit', models.IntegerField(default=5000)),
            ],
            options={
                'verbose_name': 'Rave Payment Configuration(Flutter Wave)',
                'verbose_name_plural': 'Rave Payment Configuration(Flutter Wave)',
                'managed': True,
            },
        ),
    ]
