# Generated by Django 2.0.6 on 2020-11-08 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField()),
                ('trans_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(choices=[('DONE', 'DONE'), ('NOT DONE', 'NOT DONE')], max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Currency',
                'verbose_name_plural': 'Crypto Currencies',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CryptoCurrencyAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='app name', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('api_url', models.TextField(default='https://api.whatsapp.com/send?phone=[ENTER_NUMBER]&text=I am interested in buying/selling [CRYPTO_CURRENCY] TRANSACTION ID is [TRANSACTION_ID]', help_text='WhatsApp Link with number', max_length=1000)),
                ('currencies_trading', models.TextField(default='["Bitcoin","Etherium"]', max_length=5000)),
            ],
            options={
                'verbose_name': 'Crypto Currency API',
                'verbose_name_plural': 'Crypto Currency APIs',
            },
        ),
    ]
